### ISSUE TITLE
[Feature Request] Add prod80's shader effects repo as well

### ISSUE THREAD

**Issue by Nano-Ocelot** [kevinlekiller/reshade-steam-proton#1]
Basically I'm just requesting that another popular repo https://github.com/prod80/prod80-ReShade-Repository be added to the script as well. A lot of these effects are popularly used in various presets that are found online for games. Having support for this repo of shaders would make it even easier to have this script as an all-in-one tool for reshade. Anyway, great work. This makes installing reshade so much easier than any other tool I've found out there.

**Comment by kevinlekiller** [comment]
You'll want to use the REBUILD_MERGE option, to pick up the new repo.

**Comment by Nano-Ocelot** [comment]
great, works perfectly
