### ISSUE TITLE
Unable to start tutorial

### ISSUE THREAD

**Issue by KnightJeffrey** [kevinlekiller/reshade-steam-proton#10]
So, I either need to start the tutorial or just get rid of it because its breaking my immersion in the game always having it on screen asking me to start it. The reshade settings are already set based on what Ive seen in the reshade.ini but the whole tutorial thing is just bothering me.

**Comment by kevinlekiller** [comment]
https://reshade.me/forum/troubleshooting/3500-solved-tutorial-bugs-out#23630

**Comment by KnightJeffrey** [comment]
The tutorial is already at 4

**Comment by KnightJeffrey** [comment]
Also its asking to start the tutorial because its a fresh install it doesnt go away no matter what I do

**Comment by kevinlekiller** [comment]
I'm not sure, might be better to ask on the reshade forum.

What game is it, maybe I can try it and see if I have the same issue?

**Comment by KnightJeffrey** [comment]
Skyrim special edition/ Anniversary Editon

**Comment by KnightJeffrey** [comment]
I have had reshade for skyrim in the past on windows so its a linux specific problem

**Comment by kevinlekiller** [comment]
It's a known issue with Skyrim  on Linux, the game is doing something weird which causes issues.

You need to open the reshade interface as soon as the game starts then you go to the settings and change Input Processing to Pass All Input and configure it then.

![reshade skyrim](https://user-images.githubusercontent.com/1641964/155728973-e716784b-b0fe-41d5-ae79-09e174cfbb6d.png)

**Comment by KnightJeffrey** [comment]
Thanks now all I'm missing is the effects for some reason
