### ISSUE TITLE
ReShade 5.1 doesn't work

### ISSUE THREAD

**Issue by onlyreportingissues** [kevinlekiller/reshade-steam-proton#12]
"Regarding Vulkan, the setup tool now maintains a list of applications in %LOCALAPPDATA%\ReShade\ReShadeApps.ini. If ReShade is being loaded into a Vulkan application from %LOCALAPPDATA%\ReShade\ReShade[32/64]\ReShade[32/64].dll, then it will only activate if that application executable path is in this list. Otherwise ReShade will prevent itself from loading. You can delete %LOCALAPPDATA%\ReShade\VkLayer_override.json, it is no longer used. Do note that you'll have to reinstall ReShade to all Vulkan games, previous installs are not updated automatically.
Also note that ReShade will not load in Vulkan games that are launched as administrator by default! This is because the Vulkan loader ignores user layers (in the "HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan\ImplicitLayers" registry key) when doing so, but ReShade is installed as one. If you want to use ReShade in applications that are executed as administrator, need to move the registry entry pointing to ReShade64.json to "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers" and the entry pointing to ReShade32.json entry to "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Khronos\Vulkan\ImplicitLayers". Do not attempt this if you are not familiar with the Windows registry!"

"Cemu for example runs as administrator, so ReShade won't work without doing the modifications mentioned there.

Unfortunately I only noticed the problem that the Vulkan loader ignores user layers after release. In the future this probably means the ReShade setup tool will require administrator rights to install to Vulkan games again (since "HKEY_LOCAL_MACHINE" cannot be modified without them) and things will move back into ProgramData instead of being able to install per-user (but will still be per-game and not global). But with the current released setup tool you'll have to make those changes manually. Note that ReShade 5.1 itself is not the problem here, it's entirely a setup configuration thing with setting up the right registry keys. ReShade 5.1 does work perfectly in all Vulkan apps/games, provided the registry keys are set up accordingly."

https://reshade.me/releases/7951-5-1

**Comment by kevinlekiller** [comment]
The script doesn't support Vulkan, so that won't be the issue.

I haven't had time to test 5.1 yet, but for now you can install the old version :

    RESHADE_VERSION="5.0.2" ./reshade-linux.sh

**Comment by kevinlekiller** [comment]
> If the script supported Vulkan
> Any plans to support Vulkan?

It kind of supports Vulkan for version 4 of Reshade, but it needs some changes for version 5.

> would native games be supported then also?

This is not possible, since Reshade is specifically designed for Windows. Reshade itself would need to add support for Linux.

You can find alternatives to Reshade that work on Linux here: https://github.com/kevinlekiller/reshade-steam-proton#alternatives

**Comment by onlyreportingissues** [comment]
Works normally again with the 5.2 release.

**Comment by canceralp** [comment]
> Works normally again with the 5.2 release.

Do you mean 5.2. works with Vulkan? If so, would you please show how?
