### ISSUE TITLE
ReShade 5.1 doesn't work with ME Andromeda

### ISSUE THREAD

**Issue by Kepsz** [kevinlekiller/reshade-steam-proton#14]
Hi,

With RS 5.1, Mass Effect Andromeda (Origin) complains about missing license regarding to dxgi.dll. I think that means some missing dll's.

But with the 5.0.2 version, Andromeda is working fine.
"RESHADE_VERSION="5.0.2" ./reshade-linux.sh"

**Comment by kevinlekiller** [comment]
#12

`RESHADE_VERSION="5.0.2" ./reshade-linux.sh`
