### ISSUE TITLE
[Bug] If autodetect gets the 32/64 bit wrong it still selects the incorrect d3dcompiler after correcting it

### ISSUE THREAD

**Issue by Nano-Ocelot** [kevinlekiller/reshade-steam-proton#2]
I used autodetect 32/64 bit and it got it wrong for a game by thinking it was 64 bit, so I corrected it when the script asked and told it that the game was 32 bit. I then manually chose the d3d9.dll, then it went ahead and still installed the 64 bit version of d3dcompiler_47, which obviously broke reshade from working. I had to rerun the script, uninstall and reinstall, this time choosing manual and choosing 32-bit from the beginning.

**Comment by kevinlekiller** [comment]
I think the issue is the link isn't deleted / recreated which causes the wrong file to be linked.

Thanks for the issue, will look into it.

**Comment by kevinlekiller** [comment]
Commit ed7387e might fix the issue.
