### ISSUE TITLE
A few issues running this in Source/GoldSrc games

### ISSUE THREAD

**Issue by DemonOwl** [kevinlekiller/reshade-steam-proton#21]
First off, i'll start with the one that i need help with the most. For whatever reason i can't get this to run alongside Half Life 1. The dll's are 32 bit which is correct and the files have been placed in root folder with the exe and the launch options are right. But i think the issue has to do with how half life looks for the game to run. Most of it's DLL's are in root but the ones to do with the specific game code. Half-Life's game code is stored within Half-Life/valve/Cl_dlls and Half-Life/valve/dlls. I've tried accounting for this by copy and pasting the d3d9 and d3dcompiler_47 dll files into each but the game won't launch, it's stuck in loading forever and i'm not sure what to do.

I really wish this script allowed you to specifically select which exe to install to because i think that might be causing some issues when injecting into other games as well. Most recently for me xash3d fwgs has like 3 exe files in the root folder and i have no idea if it'll find the right one to use. It also has not worked (it loads without reshade)

 When it comes to source it works fine but only with a caveat. That being you need to place the dll's inside of bin, once again because of the way the game stores it's code. Would be nice to see this accounted for in the installer (especially because pretty much all source games use the same folder systems), but it's alright.

This is definitely much more convenient than running vkBasalt tho. Kudos

**Comment by DemonOwl** [comment]
After looking more into it i've heard the dll's are supposed to be in the game's root folder but it still doesn't work either way

**Comment by kevinlekiller** [comment]
Half-Life uses OpenGL. https://www.pcgamingwiki.com/wiki/Half-Life#API

See https://github.com/kevinlekiller/reshade-steam-proton/blob/main/reshade-linux.sh#L40

**Comment by DemonOwl** [comment]
Thanks. Does that also mean i have to change the dll override?

**Comment by DemonOwl** [comment]
I changed d3d9.dll to opengl32.dll and it did nothing, i changed it in the launch options as well and it did nothing. your documentation on line 40 doesn't actually explain what that means when it comes to the actual changes you have to make. Do i have to do rename it through the script? does d3d9compiler have to change? (i did rename it through my file manager for the record and it did nothing)

**Comment by kevinlekiller** [comment]
Yes, it will output the proper one to use at the end.
