### ISSUE TITLE
Getting `Error: Could not download latest version of ReShade.` on Steam Deck

### ISSUE THREAD

**Issue by atwright147** [kevinlekiller/reshade-steam-proton#23]
Hey,

I am trying out your `reshade-steam-proton.sh` script for the first time on a 512Gb Steam Deck.

When I run the script, it is able to download shaders etc but I get the following afterwards:

```
...
Checking for Reshade updates.
----------------------------------------------------------------
Updating Reshade.
SSL_INIT
Error: Could not download latest version of ReShade.
Exiting.
```

Any help would be much appreciated :)

**Comment by kevinlekiller** [comment]
The issue was fixed in the newer script (reshade-linux.sh).

Fixed in the old script (reshade-steam-proton.sh) now in commit c3e367249be3f8ebcfc3281ce22227ddccb6bfeb

**Comment by atwright147** [comment]
It works now, thank you :)

**Comment by atwright147** [comment]
Should I be using `reshade-linux.sh` or `reshade-steam-proton.sh` on my Steam Deck?

**Comment by kevinlekiller** [comment]
reshade-linux.sh is the currently supported script

Sometimes the failed to compile error will occur, but if you click the "Reload" button in the ReShade interface a few times it will succesfully compile, it can sometimes take 3 or more times, this is an issue specific to Wine / ReShade, I'm guessing it's some kind of timing issue.

**Comment by kevinlekiller** [comment]
Also I should note that some shaders will always fail to compile, even if the reload button is used, can't remember which off the top of my head, sorry.
