### ISSUE TITLE
Error in preprocessing shaders

### ISSUE THREAD

**Issue by Hugbenny** [kevinlekiller/reshade-steam-proton#26]
Hey,

I got a "preprocessor error" during the loading of shaders after a fresh installation, and couldn't load them.
The main branch of the crosire/reshade-shaders was in fact changed recently from "master" to "slim", hence not allowing the script to download it.
Changing "master" to "slim" in reshade-linux.sh allows it to fully download the shaders, and load them once in game. 

Btw, thx a lot for this script !

**Comment by kevinlekiller** [comment]
Thanks! I'll change it to slim.
