### ISSUE TITLE
how to use this script with reshade with addon support for a game that requires it (FFXIV)?

### ISSUE THREAD

**Issue by silverhikari** [kevinlekiller/reshade-steam-proton#27]
i am moving to reshade after gshade is no longer available. but for reshade to work on FFXIV (i am using xivquicklauncher to play on linux) it requires reshade with addon support. is there a way to specify that version of reshade with the script or is there another way i should do this?

**Comment by kevinlekiller** [comment]
I'm not sure, will see what I can do.

**Comment by kevinlekiller** [comment]
`RESHADE_ADDON_SUPPORT=1 ./reshade-linux.sh`

This will install the latest version of ReShade with addon support.

**Comment by kevinlekiller** [comment]
Let me know if there are any issues, I've tried to test as many scenarios as I can think of.
