### ISSUE TITLE
Error: Could not fetch ReShade version. Exiting.

### ISSUE THREAD

**Issue by wowseirin** [kevinlekiller/reshade-steam-proton#29]
Upon the "Checking for Reshade updates." step, an error occurs: "Error: Could not fetch ReShade version. Exiting."

This happens after the script successfully completes both the "Checking for ReShade Shader updates." and the "Checking for External Shader updates." steps.

[terminal-output.txt](https://github.com/kevinlekiller/reshade-steam-proton/files/11011124/terminal-output.txt)

**Comment by kevinlekiller** [comment]
This is usually because https://reshade.me is down, I added http://static.reshade.me as a backup but that can sometimes be down also.

**Comment by domglusk** [comment]
Getting this error, reshade website isn't down either.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Same error here

**Comment by kevinlekiller** [comment]
I'm not experiencing the issue personally.

Maybe do `curl -sL https://reshade.me > /tmp/reshade.html` and upload that to a gist, then I could see what you guys are getting.

**Comment by micros24** [comment]
I'm also having this error. I uploaded the gist here. 
https://gist.github.com/micros24/df93fd586036c1da017c0ef59d48f8ff
I'm not sure if this is what you're looking for. I just searched what gist is and dragged the file to the blank field in the create gist page. I hope it helps

**Comment by kevinlekiller** [comment]
Thanks.

**Comment by kevinlekiller** [comment]
I looked at your gist and it's the same as what I get, so I'm not sure why you are getting the error?

Just to make sure, are you using the latest version of the script?

**Comment by kevinlekiller** [comment]
Pushed a change, let me know if that works.

**Comment by kevinlekiller** [comment]
No worries.
