### ISSUE TITLE
Error: Could not fetch ReShade version.

### ISSUE THREAD

**Issue by pipes80-collab** [kevinlekiller/reshade-steam-proton#32]
When i try to use reshade steam version i take this error: Error: Could not fetch ReShade version.

**Comment by kevinlekiller** [comment]
https://github.com/kevinlekiller/reshade-steam-proton/issues/29

https://github.com/kevinlekiller/reshade-steam-proton/commit/d7430722ff2e6534b5320c62f1cc3c32a985d4e4

**Comment by kevinlekiller** [comment]
reshade-steam-proton.sh is obsolete, I'll remove it eventually

**Comment by Melmartel** [comment]
Allô

**Comment by Melmartel** [comment]
Kev?? C melane on te cherche

**Comment by Melmartel** [comment]
Is sonebody have talk to kevinlekiller please its my cousin and he desapear

**Comment by Melmartel** [comment]
Kev???
