### ISSUE TITLE
ReShade with full add-on support

### ISSUE THREAD

**Issue by yaomtc** [kevinlekiller/reshade-steam-proton#36]
The main version of ReShade has a restriction: with high network activity detected it will lock down the z-buffer to prevent using it for cheating. Playing some online games with the unlocked z-buffer version can result in bans, or the developers banning the use of ReShade entirely.

Can you provide a function to download the "full add-on support" version? 

Should I run their .exe in Wine?

https://reshade.me/downloads/ReShade_Setup_5.8.0_Addon.exe

**Comment by Azurion42** [comment]
I'm looking for info on this too, I want to use it for FFXIV but can't figure out how to install it.

**Comment by yaomtc** [comment]
I found it in the comments of the shell script!

 `RESHADE_ADDON_SUPPORT=1 ./reshade-linux.sh`

**Comment by yaomtc** [comment]
Also, make sure to go into the global preprocessor definitions and add RESHADE_DEPTH_INPUT_IS_REVERSED, set to 0. It's set to 1 by default. And if you're using MXAO, enable MXAO_SMOOTHNORMALS.
