### ISSUE TITLE
How to apply vkBasalt directly to gamescope

### ISSUE THREAD

**Issue by wheaney** [kevinlekiller/reshade-steam-proton#42]
I know this is outside the scope of this repo, but this is the only place I've seen mention of the following:

> Since [gamescope](https://github.com/Plagman/gamescope/) can use Vulkan, you can run vkBasalt on gamescope itself, instead of on the game.

Has anyone done this or seen any discussion around it elsewhere? I'm trying to figure out how I can apply a shader to *all of gamescope*, and not just specific games. And yes, I know that reshade support is already in the gamescope pipeline for a future release, but that won't actually work for my use case, so I'd like to figure this out with vkBasalt. Any help would be appreciated.

**Comment by Saroumane** [comment]
You can install vkbasalt ( https://github.com/DadSchoorse/vkBasalthttps://github.com/DadSchoorse/vkBasalt ) then use it like this 
: 
`$ ENABLE_VKBASALT=1 gamescope -- vkcube`
(replace vkcube by your game)

if you use Steam , edit Launch Options like that : 
`ENABLE_VKBASALT=1 gamescope -- %command%`

If you prefer to use a dedicated script, your Launch Options may look like this : 
`~/myscript.sh %command% `

And for myscript.sh
```
#!/bin/bash
ENABLE_VKBASALT=1 gamescope -- "$@"
```

(Of course you can add gamescope options before the double dash.)
