### ISSUE TITLE
Reshade not working with Prince of Persia The Sands of Time

### ISSUE THREAD

**Issue by sh1sh1n11** [kevinlekiller/reshade-steam-proton#5]
Hi Kevinlekiller,

Firstly, thanks so much for working on this script! I tried using the script on Prince of Persia The Sands of Time, running via Steam on Arch Linux.

My setup:
Kernel: 5.15.7-zen1-1-zen
Proton-6.21-GE-2
Wine-Staging (6.23-1)
GPU: Nvidia GTX 1070 Max-Q
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

So the issue is that when I first boot up the game after installing reshade using the provided shell script, it shows the initial overlay of reshade in-game for a few seconds. When I try using the 'Home' button on my keyboard to bring down the reshade console/menu, it does nothing.

The script identified POP Sands of Time as a 32-bit directx9 game, and hence suggested me to use the below parameters. Which I added to my game in steam.

WINEDLLOVERRIDES="d3dcompiler_47=n;d3d9=n,b" %command%

Also, if it helps, when the reshade overlay is briefly displayed as the game launches, when I quickly press the 'Home' button to activate it, I see a thin strip (of the console/menu?) at the very top of the screen, but it has no contents. And within seconds, that too disappears, before the game even displays its menu screen.

Any help or pointers to fix this issue would be very much appreciated.Thanks again!

**Comment by sh1sh1n11** [comment]
Looks like steam overlay is disabled on purpose by the developers for this game. Or any overlay for that matter. No wonder the Reshade overlay does not show up.

https://github.com/ValveSoftware/Proton/issues/3209

Is there a way to configure / generate the 'ReshadePreset.ini' file from outside the game? So far I've tried generating one from another game, but POP Sands of Time gets stuck after few seconds of gameplay. The only shaders I had enabled on the other game are FXAA and FakeHDR.

Also, I had used reshade on this game with many more effects such as DOF, RTGI, etc on Windows without any issues. Same game on Steam. The Reshade overlay somehow worked there, including the steam overlay.

**Comment by kevinlekiller** [comment]
Hi, I don't own that game so can't test unfortunately.

Have you tried vkBasalt with this game? It doesn't have a overlay so it shoudln't interfere with the game loading up.

**Comment by sh1sh1n11** [comment]
No worries @kevinlekiller , and thanks so much for offering an alternative solution. And yes indeed. I just learnt about vkBasalt today and got it to work with POP SOT.

Got another question for you though. Is there a OpenGL post processing tool for native Linux games? I was really wanting to use some post processing on good old valve games like Half-Life 2.

PS - Please feel free to close this issue. Thanks much for your prompt reply. Much appreciated!

**Comment by kevinlekiller** [comment]
I haven't found anything for OpenGL native to Linux, but there are some solutions you can try:

If you run Half-Life 2 using Vulkan ( see https://www.pcgamingwiki.com/wiki/Half-Life_2#API | https://www.gamingonlinux.com/2021/10/half-life-2-and-the-episodes-get-a-beta-with-vulkan-dxvk-and-more/ ), then you can use vkBasalt.

If you use the Windows version through proton, then DXVK is used (since the Windows version uses Directx 9) and you can then use ReShade or vkBasalt.

**Comment by sh1sh1n11** [comment]
That sounds great! Thank you so much @kevinlekiller! I will give the HL-2 Vulkan thing a try to begin with. Have a great day!
