### ISSUE TITLE
How to use with games from heroic game launcher? Tried but failed to launch games.

### ISSUE THREAD

**Issue by rairay91** [kevinlekiller/reshade-steam-proton#62]
I did my best and tried all possible way to use it, but game won't launch.
I have no idea where to put WINEDLLOVERRIDE"d3dcompiler_47=n;dxgi=n,b" argument?

**Comment by rporter220** [comment]
I'm not sure if the heroic game launcher allows you to do dll overrides (I don't use heroic).
But if you can open the wine configuration, these go under the libraries tab. You would just enter d3dcompiler_47 and dxgi in that tab and then make sure d3dcompiler_47 is set to native and dxgi is native then built-in.

![image](https://github.com/user-attachments/assets/823d8329-01c4-434d-9fc4-4feede34ce90)

**Comment by rairay91** [comment]
Thanks, that worked.
