### ISSUE TITLE
Failed to Compile - Ternary Operator

### ISSUE THREAD

**Issue by Recently-Coco** [kevinlekiller/reshade-steam-proton#63]
Hello, 
I am attempting to get this running with FFXIV and am encountering the following error:

"ERROR | Failed to compile 'Z:\home\coco\.local\share\reshade\ReShade_shaders\Merged\Shaders\DPX.FX"
"E5017: Aborting due to not yet implemented feature: Ternary operator."

This appears to apply the same to every .fx listed on the home tab. 

![image](https://github.com/user-attachments/assets/a69c20f3-56dd-4b8a-b06a-7164119952ed)

I cannot seem to find anyone else with this issue, and the installation instructions do not seem to help.

**Comment by Foibless** [comment]
Need to move d3dcompiler_47.dll from the FFXIV folder to ~/.xlcore/wineprefix/drive_c/windows/system32/ back up the old dll before replacing it, just in case

**Comment by Recently-Coco** [comment]
Ah! that did it! Solved!
