### ISSUE TITLE
resahde full add-ons support

### ISSUE THREAD

**Issue by tanuki2k** [kevinlekiller/reshade-steam-proton#64]
How would I go about getting reshade with full add-on support working? Thanks in adviace :D

**Comment by Sasha-Acoiners** [comment]
RESHADE_ADDON_SUPPORT=1 is the command you want to use. You use that, and then the command to run the script (Which is obviously different depending on where you saved the .sh file to.) I've posted an example image below.

![Reshade addon example](https://github.com/user-attachments/assets/8c6796bf-4c1d-448e-b652-0dc1845196f5)

**Comment by tanuki2k** [comment]
thank you! :D

**Comment by tanuki2k** [comment]
thanks!

**Comment by brianx87** [comment]
Very nice!

You should add this to the installation instructions!
