### ISSUE TITLE
Reshade 6.3.3 failing all shader compiles under XIVLauncher FF14

### ISSUE THREAD

**Issue by Marakai** [kevinlekiller/reshade-steam-proton#73]
I am running Kubuntu 24.04 LTS and running Final Fantasy 14 under XIVLauncher 1.1.0.

It runs fine and problem-free in that mode. It's the stand-alone Square Enix client, not run through Steam.

Installing RS 6.3.3 with `RESHADE_ADDON_SUPPORT=1  ./reshade-linux.sh` and receive

```
------------------------------------------------------------------------------------------------
ReShade installer/updater for Linux games using wine or proton.
------------------------------------------------------------------------------------------------

Checking for ReShade Shader updates.
Checking for External Shader updates.
------------------------------------------------------------------------------------------------
Using the latest version of ReShade (6.3.3_Addon).

Do you want to (i)nstall or (u)ninstall ReShade for a DirectX or OpenGL game?
(i/u): i
Supply the folder path where the main executable (exe file) for the game is.
(Control+c to exit)
Game path: /games/FFXIV/game
Is this path correct? "/games/FFXIV/game"
(y/n) y
Do you want ./reshade-linux.sh to attempt to automatically detect the right dll files to use for ReShade?
(y/n) y
We have detected the game is 64 bits, we will use dxgi.dll as the override, is this correct?
(y/n) y
Linking ReShade files to game directory.
Linking ReShade64.dll to dxgi.dll.
------------------------------------------------------------------------------------------------
Done.
If you're using Steam, right click the game, click properties, set the 'LAUNCH OPTIONS' to: WINEDLLOVERRIDES="d3dcompiler_47=n;dxgi=n,b" %command%
If not, run the game with this environment variable set: WINEDLLOVERRIDES="d3dcompiler_47=n;dxgi=n,b"
The next time you start the game, open the ReShade settings, go to the 'Settings' tab, if they are missing, add the Shaders folder location to the 'Effect Search Paths', add the Textures folder to the 'Texture Search Paths', these folders are located inside the ReShade_shaders folder, finally go to the 'Home' tab, click 'Reload'.
```

This will still launch the game, as usual, but the entire list of shaders fails to compile and checking the Home tab I see all of them failing with the message:

```
error: F__PostProcessVS: <anonymous>:X:Y: E5017: Aborting due to not yet implemented feature: Ternary operator.
```

where X and Y are "random" numbers, likely line numbers or similar.

I have added

`WINEDLLOVERRIDES="d3dcompiler_47=n;dxgi=n,b"`

to the XIVLauncher settings Additional Game Arguments. The Texture and Shader directories are correctly set in ReShade settings. Out of curiosity, I tried running older versions of ReShade (6.1.1 and 6.2.0) but these make the game crash hard and I didn't pursue that any further.

For completeness, I've also made a little launcher script

```
#!/usr/bin/env bash

export WINEDLLOVERRIDES="d3dcompiler_47=n;dxgi=n,b" 
/usr/games/xivlauncher-core
```

just to be redundant on the environment variable, but to no avail.

**Comment by Marakai** [comment]
Update: FFXIV uses DXVK. I'm not knowledgeable enough as to where something like ReShade "kicks in": the game still talks DX11, and only at the underlying driver level does it "speak" Vulkan.

**Comment by rporter220** [comment]
Sounds similar to the issue I was having until I found:
https://github.com/kevinlekiller/reshade-steam-proton/issues/63

It's a closed issue that you need to:

> Need to move d3dcompiler_47.dll from the FFXIV folder to ~/.xlcore/wineprefix/drive_c/windows/system32/ back up the old dll before replacing it, just in case

After I moved that file, all the shaders would compile like normal.

**Comment by Marakai** [comment]
That indeed is/was the solution! You are my hero. Should arguably go into the script. If/when I have a few cycles for a PR.
