### ISSUE TITLE
Cannot cd into reshade_shaders folder

### ISSUE THREAD

**Issue by Ranguna** [kevinlekiller/reshade-steam-proton#8]
1. copied the script from https://github.com/kevinlekiller/reshade-steam-proton/blob/main/reshade-linux.sh
2. Placed it in my home folder
3. Changed permissions to execute it
4. executed it and was greeted with the following:

> ./reshade-linux.sh: line 298: cd: $HOME/.reshade/ReShade_shaders: No such file or directory

Adding `mkdir -p $HOME/.reshade/ReShade_shaders` above the commands that attempt to cd into into seems to have fixed it.

Is there any particular reason to omit this mkdir command ?
If it was just missed, I can do a quick PR.

**Comment by Ranguna** [comment]
Created PR :+1:

**Comment by kevinlekiller** [comment]
Thanks, I probably manually created the dir so never ran into the issue.
